### ISSUE TITLE
jQuery issue

### ISSUE THREAD

**Issue by forepointmc** [jaredpalmer/presspack#11]
Hi, I think there is a problem with jquery in this theme. It's being loaded twice from cdn and the bundle. If you deregister jquery in wordpress so the file doesn't load in the header, then jquery goes undefined even though you're importing from the bundle in index.js

This causes problems when trying to call functions from Bootstrap loaded from Webpack, functions work fine when called via data attributes, but same functions are undefined when called by js.

I discovered this when I was trying to call a modal with bs function $('#myModal').modal('show')

**Comment by turansadri** [comment]
@forepointmc you can remove jQuery from package.json dependencies and only use the one which Wordpress includes automatically. I just learned that Webpack lets you define "externals" where you can define external jQuery and use that in your bundle.

What I did was
- removed jQuery from package.json and re-installed node_modules
- added **externals: { jquery: 'jQuery' }** to weback.config.js (check the link below)
- imported jQuery in index.js: **import $ from 'jquery';**

Read the part about "Adding External jQuery or other Libraries" here. I followed his instructions.
https://www.ibenic.com/configuring-webpack-wordpress/

More info about Webpack's externals:
https://webpack.js.org/configuration/externals/
