### ISSUE TITLE
Update to Webpack 4

### ISSUE THREAD

**Issue by leifniem** [jaredpalmer/presspack#13]
It's just a suggestion, since Webpack had a lot of updates in the major releases since.

**Comment by leifniem** [comment]
Things that would need to be considered:

- Replacing [Extract Text Plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) with [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) as mentioned in its docs
- Switching from the UglifyJsPlugin to the new [Optimization Config](https://webpack.js.org/configuration/optimization/) or adding the UglifyJsPlugin manually and moving the config to the Optimization Config
- Updating Dependencies (like removing auto-prefixer)

**Comment by aficiomaquinas** [comment]
+1

**Comment by mxmtsk** [comment]
Hey guys, we've forked and updated to Webpack 4. Care to test it out? :)
https://github.com/MOVACT/presspack

On the fork I'm planning to add some more features like image optimization etc but if this basic setup works I might add a PR for the original repo too

**Comment by jaredpalmer** [comment]
Go for it!

**Comment by jaredpalmer** [comment]
Make a PR!
