### ISSUE TITLE
Use ddev and presspack?

### ISSUE THREAD

**Issue by landwire** [jaredpalmer/presspack#22]
Hi there,
I would like to use Presspack with my ddev environment.
Ist that possible? 

https://www.drud.com/ddev-local/one-minute-wordpress/

**Comment by krystianjj** [comment]
Hi,
I don't use ddev and I don't know how exactly work but if you properly configure webpack you can use extra features from presspack like bundling, hot reload etc.

Personally I think the presspack is very good and it'a all you need in 4 steps.

1. clone repo
2. docker-compose up
3. yarn install
4. yarn start

That's it :)
