### ISSUE TITLE
Cannot update wordpress or install/delete plugins

### ISSUE THREAD

**Issue by artjomzab** [jaredpalmer/presspack#27]
I am on OSX and this seems to be a permission related issue. Neither can I upgrade wordpress nor install/delete any plugin. 

I think apache tries to access wp-content on the host system. Since apache is running as  www-data:www-data and such user/group does not exist on OSX, writing to wp-content fails.

I modified envvars in /etc/apache2 and changed the user to a user known to OSX. I even did a chmod -R 777 😄 however it did not solve the problem?

Does anyone have a solution for this?

**Comment by braisgil** [comment]
Same issue here

**Comment by artjomzab** [comment]
@braisgil ssh into the wordpress container:

`docker exec -it "container_name" sh`

and set permissions:

`sudo chown -R www-data:www-data /var/www/html`

**Comment by cjstage** [comment]
I believe this is a container specific issue since I'm still using `wordpress:4.7.5-apache`.  For some reason that container doesn't have the same permission issue.  Though, two commands to fix the permissions isn't too much of a hassle; I just run the updater as I'm setting up the rest of wordpress.

**Comment by michalkrynski** [comment]
You can also add whole wp-content as volume in docker-compose.yml
`...
- ./wp-content/:/var/www/html/wp-content/
...`

**Comment by infn8** [comment]
Confirmed that the @artjomzab solution worked for me except that `sudo` was not required as I ended up logged in as root.
