### ISSUE TITLE
Persist database in version control

### ISSUE THREAD

**Issue by FistMeNaruto** [jaredpalmer/presspack#4]
Is it possible to store the .data folder in version control?

At the moment docker pulls `/var/lib/mysql` from db container to `.data/db`, but `.data` is owned by root and `.data/db` is owned by 999 and group kvm. This causes permission issues when trying to commit the `.data` folder to git.

I'm not sure if it is possible to version control the database, but that would allow multiple developers to work on the same project at the same time and make the development even easier by solving the issues of database migrations.

**Comment by b4dnewz** [comment]
You should be able to fix it by adding this line to the database service in docker-compose file:
```yml
user: "1000:50"
```
When you run `docker-compose up` this will create all the files inside the shared volume owned by 1000 (you user id), 50 (the staff group inside mysql container).

You can also decide to make it more dinamic by getting the current user id before running the command for example: `export UID=(id -u):(id -g)` and than use it as variable inside docker-compose file.

PS: I've never tried to version control the database folder but this should solve your permission issue at least, let me know if is working.
