### ISSUE TITLE
Problem with BrowserSync

### ISSUE THREAD

**Issue by krystianjj** [jaredpalmer/presspack#9]
Hi, 
I just installed presspack and everything working except BrowserSync :/
I working on windows

On localhost:9009 working great
But localhost:4000 doesn't 

After run command: yarn start I have

> λ yarn start
yarn run v1.7.0
$ set NODE_ENV=development && node ./scripts/start.js
clean-webpack-plugin: C:\temp\presspack\scripts\build has been removed.

and browser with BrowserSync doesn't start

UPDATE:
when I change

> const DEV = process.env.NODE_ENV === 'development';
to
const DEV = 'development';
it's working 

Now I must find how to read properly process.env in windows

**Comment by jaredpalmer** [comment]
Use cross-env package

**Comment by krystianjj** [comment]
Thank you. Now works great!
